### ISSUE TITLE
starting failed

### ISSUE THREAD

**Issue by ghost** [husam212/MITMer#2]
sudo python2 ./mitmer.py 
lstat(./dvips) failed ...
./dvips: No such file or directory
python2: ../../../texk/kpathsea/progname.c:316: remove_dots: Assertion `ret' failed.

**Comment by husam212** [comment]
This seem to be a scapy bug, check this out https://github.com/pwnieexpress/2014-security-tools-review/blob/master/deep-dive/dhcpig.md

**Comment by troygt** [comment]
Scapy has a dependency on python-pyx, which was fully ported over to python 3.  It won't work. You either have to remove python-pyx or go find and install the python 2 version of pyx, (0.12.x) I think.

**Comment by Andresart21** [comment]
tengo el mismo error cual es la solucion entonces
