### ISSUE TITLE
callback error

### ISSUE THREAD

**Issue by ghost** [husam212/MITMer#5]
user@sys:~/Sec/MITMer$ sudo ./mitmer.py 
Initializing
No interface specified, using default (wlan0)
No domains specified, using default [facebook.com]
Scanning network
Host detected 192.168.178.39
Spoofing 192.168.178.39
Creating fake pages
callback failure !
TypeError: reply() takes exactly 2 arguments (3 given)
callback failure !
TypeError: reply() takes exactly 2 arguments (3 given)

**Comment by husam212** [comment]
What version of python-nfqueue are you using? I use the one available in AUR (0.4), not sure about other distros.

**Comment by mms-systems** [comment]
what do you mean with AUR 0.4?

**Comment by husam212** [comment]
AUR is the Arch user Repo, something related to Archlinux. 0.4 is the version of python-nfqueue I use and it is working flawlessly, check if you are using an older version, it might be the reason causing that callback error.
